name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: yarn tsc
    - name: Run tests
      run: npm run test