name: Publish core

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/core    

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: remove overlying workspace
      run: rm ../../yarn.lock && rm ../../package.json

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn tsc

    - name: Bundle
      run: npx webpack      

    - name: Version
      run: npm version patch -m "Upgrade to %s"
    
    - name: Publish
      run: npm publish      

      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DATA_STORY }}