name: Publish core

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/core    

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Check version
      id: check
      run: |
        PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
        echo "Version: $PACKAGE_VERSION"
        HTTP_STATUS=$(curl --silent --head --write-out "%{http_code}" --output /dev/null https://registry.npmjs.org/@data-story/core/$PACKAGE_VERSION)

        if [ $HTTP_STATUS -eq 200 ]; then
          echo "Version $PACKAGE_VERSION already exists. Exiting the action script."
          echo "exit0 here but ignoring it"
        else
          echo "Version does not exist."
        fi

    - name: remove overlying workspace
      run: rm ../../yarn.lock && rm ../../package.json

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn tsc

    - name: Bundle
      run: npx webpack      
    
    - name: Publish
      run: npm publish      

      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DATA_STORY }}