name: Publish ui

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Check version
      id: check
      run: |
        PACKAGE_VERSION=$(node -p -e "require('./packages/ui/package.json').version")
        echo "Version: $PACKAGE_VERSION"
        HTTP_STATUS=$(curl --silent --head --write-out "%{http_code}" --output /dev/null https://registry.npmjs.org/@data-story/ui/$PACKAGE_VERSION)

        if [ $HTTP_STATUS -eq 200 ]; then
          echo "Version $PACKAGE_VERSION already exists. Exiting the action script."
          echo "VERSION_EXISTS=true" >> $GITHUB_ENV
        else
          echo "Version does not exist."
          echo "VERSION_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      if: ${{ env.VERSION_EXISTS == 'false' }}    
      run: yarn

    - name: Build
      if: ${{ env.VERSION_EXISTS == 'false' }}    
      run: yarn build

    - name: Publish
      if: ${{ env.VERSION_EXISTS == 'false' }}    
      run: |
        yarn config set -H npmScopes.data-story.npmRegistryServer "https://registry.npmjs.org/"
        yarn config set -H npmScopes.data-story.npmAuthToken "${{ secrets.NPM_DATA_STORY }}"
        cd packages/ui && yarn npm publish
