name: tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the package
      uses: actions/checkout@v2

    - name: Install
      run: composer install

    - name: Run tests
      run: ./vendor/bin/phpunit tests --testdox