name: Test core

on: [push, pull_request]

jobs:
  test:
    defaults:
      run:
        working-directory: ./packages/core  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'
    - name: remove overlying workspace
      run: rm  -f ../../yarn.lock && rm  -f ../../package.json
              
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn tsc
    - name: Run tests
      run: yarn test